//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGE.SeletivaAnalista.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class analista_vaga_perfil_barema
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public int pontos { get; set; }
        public int minimo { get; set; }
        public int maximo { get; set; }
        public Nullable<int> acada { get; set; }
        public int idvagaperfil { get; set; }
        public string tipo { get; set; }
        public string nivel { get; set; }
    
        public virtual analista_vaga_perfil analista_vaga_perfil { get; set; }
    }
}
