//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGE.SeletivaAnalista.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class analista_perfil
    {
        public int id { get; set; }
        public string perfil { get; set; }
    }
}
