//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGE.SeletivaAnalista.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class analista_inscrito_documento
    {
        public int id { get; set; }
        public string tipo_documento { get; set; }
        public string nome_desc { get; set; }
        public string link { get; set; }
        public System.DateTime dtenvio { get; set; }
        public int id_inscricao { get; set; }
        public Nullable<int> idvagaperfilbarema { get; set; }
        public string pontuar { get; set; }
        public string detalhe { get; set; }
    }
}
