//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGE.SeletivaAnalista.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class analista_barema_pontuacao
    {
        public int id_pontuacao { get; set; }
        public int id_inscricao { get; set; }
        public int idvagaperfilbarema { get; set; }
        public int pontuacao { get; set; }
    }
}
