//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGE.SeletivaAnalista.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class analista_inscricao
    {
        public int id_inscricao { get; set; }
        public int idinscrito { get; set; }
        public int idvaga { get; set; }
        public int idperfil { get; set; }
        public Nullable<int> nota { get; set; }
        public System.DateTime dtinscricao { get; set; }
        public int etapa { get; set; }
        public int processo_seletivo { get; set; }
        public string nivel { get; set; }
    }
}
