//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGE.SeletivaAnalista.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class analista_inscrito
    {
        public int id { get; set; }
        public string aprovado { get; set; }
        public string pcd { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public string rg { get; set; }
        public string cart_prof { get; set; }
        public System.DateTime dtnasc { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string complemento { get; set; }
        public string cep { get; set; }
        public int idcidade { get; set; }
        public string tel_fixo { get; set; }
        public string tel_celular { get; set; }
        public string e_mail { get; set; }
        public System.DateTime dtcadastro { get; set; }
        public string observacao { get; set; }
    }
}
