//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGE.SeletivaAnalista.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seletiva_analistas_002Entities : DbContext
    {
        public seletiva_analistas_002Entities()
            : base("name=seletiva_analistas_002Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<analista_barema_inscricao_pontuacao> analista_barema_inscricao_pontuacao { get; set; }
        public DbSet<analista_barema_pontuacao> analista_barema_pontuacao { get; set; }
        public DbSet<analista_cidade> analista_cidade { get; set; }
        public DbSet<analista_experiencia_profissional> analista_experiencia_profissional { get; set; }
        public DbSet<analista_inscricao> analista_inscricao { get; set; }
        public DbSet<analista_inscrito> analista_inscrito { get; set; }
        public DbSet<analista_inscrito_documento> analista_inscrito_documento { get; set; }
        public DbSet<analista_perfil> analista_perfil { get; set; }
        public DbSet<analista_uf> analista_uf { get; set; }
        public DbSet<analista_vaga> analista_vaga { get; set; }
        public DbSet<analista_vaga_perfil> analista_vaga_perfil { get; set; }
        public DbSet<analista_vaga_perfil_barema> analista_vaga_perfil_barema { get; set; }
    }
}
